"""Bake warp map, beats and lyric timing (in FINAL time) into src/data.js."""
import json, numpy as np
ROOT = __file__.rsplit('/tools/', 1)[0]
w = json.load(open(f'{ROOT}/audio/warp.json')); t = np.array(w['t']); T = np.array(w['T'])
words = json.load(open(f'{ROOT}/audio/words.json'))
LAT = 0.02  # measured rubberband latency
f = lambda x: round(float(np.interp(x, t, T)) + LAT, 4)
PER, PH = 60 / 132.0, 0.27273
beats = [f(PH + k * PER) for k in range(0, 400) if PH + k * PER < 154.0]
lines = [{'t0': s, 't1': e, 'T0': f(s), 'T1': f(e), 'text': txt, 'words': [{'w': ww, 'T': f(tt)} for ww, tt in ws]} for s, e, txt, ws in words]
data = {'warp': {'t': w['t'][::5], 'T': [round(x + LAT, 4) for x in w['T'][::5]]}, 'cut': round(w['cut'], 4), 'end': round(w['end'], 4),
        'beats': beats, 'lines': lines}
open(f'{ROOT}/src/data.js', 'w').write('// generated by tools/make_data.py\nconst DATA = ' + json.dumps(data, ensure_ascii=False) + ';\n')
print(len(beats), 'beats; cut', data['cut'], 'end', data['end'])
